#!/bin/sh
# -------------------------------------------------------------------------------
# Post-remove script for vault-cert-manager
# -------------------------------------------------------------------------------
set -e

if [ -d /run/systemd/system ]; then
    systemctl daemon-reload >/dev/null 2>&1 || true
fi

if [ "$1" = "purge" ]; then
    rm -rf /etc/vault-cert-manager
fi
