#!/bin/sh
# -------------------------------------------------------------------------------
# Pre-remove script for vault-cert-manager
# -------------------------------------------------------------------------------
set -e

if [ -d /run/systemd/system ]; then
    deb-systemd-invoke stop vault-cert-manager.service >/dev/null 2>&1 || true
fi
